/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VButtons: typeof import('./src/components/buttons/VButtons.vue')['default']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardApp: typeof import('./src/components/cardapp/VCardApp.vue')['default']
    VCardButton: typeof import('./src/components/cardapp/VCardButton.vue')['default']
    VCardClickable: typeof import('./src/components/cardapp/VCardClickable.vue')['default']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VInputField: typeof import('./src/components/inputs/VInputField.vue')['default']
    VMain: typeof import('vuetify/lib')['VMain']
    VModalCondition: typeof import('./src/components/modals/VModalCondition.vue')['default']
    VModalLarge: typeof import('./src/components/modals/VModalLarge.vue')['default']
    VRow: typeof import('vuetify/lib')['VRow']
    VSimpleTable: typeof import('vuetify/lib')['VSimpleTable']
    VStepperComp: typeof import('./src/components/stepper/VStepperComp.vue')['default']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTableAction: typeof import('./src/components/tables/VTableAction.vue')['default']
    VToast: typeof import('./src/components/toasts/VToast.vue')['default']
  }
}
