/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VAvatarComp: typeof import('./src/components/avatar/VAvatarComp.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VButtons: typeof import('./src/components/buttons/VButtons.vue')['default']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardApp: typeof import('./src/components/cardapp/VCardApp.vue')['default']
    VCardBanner: typeof import('./src/components/cardapp/VCardBanner.vue')['default']
    VCardClickable: typeof import('./src/components/cardapp/VCardClickable.vue')['default']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCheckbox: typeof import('vuetify/lib')['VCheckbox']
    VCheckBoxComp: typeof import('./src/components/CheckBox/VCheckBoxComp.vue')['default']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFeedBack: typeof import('./src/components/feedback/VFeedBack.vue')['default']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VInputField: typeof import('./src/components/inputs/VInputField.vue')['default']
    VMain: typeof import('vuetify/lib')['VMain']
    VModalCondition: typeof import('./src/components/modals/VModalCondition.vue')['default']
    VModalLarge: typeof import('./src/components/modals/VModalLarge.vue')['default']
    VPills: typeof import('./src/components/pills/VPills.vue')['default']
    VRadio: typeof import('vuetify/lib')['VRadio']
    VRadioBtnComp: typeof import('./src/components/RadioButton/VRadioBtnComp.vue')['default']
    VRadioGroup: typeof import('vuetify/lib')['VRadioGroup']
    VRow: typeof import('vuetify/lib')['VRow']
    VSimpleTable: typeof import('vuetify/lib')['VSimpleTable']
    VStepperComp: typeof import('./src/components/stepper/VStepperComp.vue')['default']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabItem: typeof import('vuetify/lib')['VTabItem']
    VTableAction: typeof import('./src/components/tables/VTableAction.vue')['default']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsItems: typeof import('vuetify/lib')['VTabsItems']
    VToast: typeof import('./src/components/toasts/VToast.vue')['default']
  }
}
