/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VButtons: typeof import('./src/components/buttons/VButtons.vue')['default']
    VMain: typeof import('vuetify/lib')['VMain']
    VStepper: typeof import('./src/components/stepper/VStepper.vue')['default']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
  }
}
